### ISSUE TITLE
How to connect to multiple DB?

### ISSUE THREAD

**Issue by pablosproject** [svtslv/nestjs-knex#12]
Hi, thanks for this package. I have a question about its usage with more than a single database? 
Should I have to manually assign a token to the nest module to have injected the correct knex instance?

**Comment by svtslv** [comment]
```ts
KnexModule.forRoot({}, 'secondConnection')
@InjectKnex('secondConnection') private readonly knex: Knex
```

**Comment by pablosproject** [comment]
Great, thanks for the quick answer.

**Comment by akaNightmare** [comment]
@pablosproject need to implement `onApplicationShutdown` for disconnecting from DB
